"""
build_vault.py — Generate an encrypted vault.js for token-gated analyses.

Each analysis is encrypted with AES-256-GCM using a key derived from a secret
token (SHA-256 of the token). The published vault.js contains only:
  - an opaque id  = SHA-256("vault-id:" + token)   (does NOT reveal the token)
  - a base64 blob = IV(12 bytes) || ciphertext || GCM tag

Without the token it is cryptographically infeasible to read an analysis,
so the dashboard opens completely blank.

Tokens live in vault_tokens.json (gitignored) and never reach the repo.
The browser decrypts with the Web Crypto API using the token from the URL (?t=).

Usage:  python build_vault.py
"""
import os
import re
import json
import base64
import hashlib
import secrets

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

BASE = os.path.dirname(os.path.abspath(__file__))
TOKENS_FILE = os.path.join(BASE, "vault_tokens.json")
DATA_FILE = os.path.join(BASE, "analysis_data.js")
OUTPUT_FILE = os.path.join(BASE, "vault.js")


def parse_analysis_data(path):
    """Extract analysisResults, consolidatedReport and consolidatedReportTime
    from the legacy analysis_data.js bundle."""
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    # results array (valid JSON between the assignment and the next const)
    m = re.search(r"const analysisResults\s*=\s*(\[.*?\]);\s*\nconst consolidatedReport",
                  text, re.DOTALL)
    results = json.loads(m.group(1)) if m else []

    # report (a JSON-encoded string literal)
    m = re.search(r"const consolidatedReport\s*=\s*(\".*?\");\s*\nconst consolidatedReportTime",
                  text, re.DOTALL)
    report = json.loads(m.group(1)) if m else ""

    # report timestamp (single-quoted)
    m = re.search(r"const consolidatedReportTime\s*=\s*'([^']*)'", text)
    report_time = m.group(1) if m else ""

    return results, report, report_time


def vault_id(token):
    return hashlib.sha256(("vault-id:" + token).encode("utf-8")).hexdigest()


def encrypt(payload_obj, token):
    key = hashlib.sha256(token.encode("utf-8")).digest()          # AES-256 key
    iv = secrets.token_bytes(12)                                  # GCM nonce
    plaintext = json.dumps(payload_obj, ensure_ascii=False).encode("utf-8")
    ciphertext = AESGCM(key).encrypt(iv, plaintext, None)         # ct || tag
    return base64.b64encode(iv + ciphertext).decode("ascii")


def main():
    with open(TOKENS_FILE, "r", encoding="utf-8") as f:
        tokens = json.load(f)

    results, report, report_time = parse_analysis_data(DATA_FILE)

    # Map source data per analysis name. Currently only the bundled one exists;
    # add more entries here (or extend the pipeline) as new analyses are created.
    sources = {
        "Marcelo Baptista de Oliveira": {
            "name": "Marcelo Baptista de Oliveira",
            "results": results,
            "report": report,
            "reportTime": report_time,
        }
    }

    vault = {}
    for name, token in tokens.items():
        payload = sources.get(name)
        if not payload:
            print(f"  ! no source data for '{name}', skipping")
            continue
        vault[vault_id(token)] = encrypt(payload, token)
        print(f"  + encrypted '{name}'  ({len(payload['results'])} results)")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Encrypted analyses vault — generated by build_vault.py.\n")
        f.write("// Each value is AES-256-GCM (base64 of IV||ciphertext||tag),\n")
        f.write("// decryptable only with the secret token carried in the URL (?t=).\n")
        f.write("window.VAULT = " + json.dumps(vault, ensure_ascii=False, indent=2) + ";\n")

    print(f"Wrote {OUTPUT_FILE} with {len(vault)} analysis(es).")


if __name__ == "__main__":
    main()
